---
title: "Kanalkodierung Simulation"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: beamer_presentation
params:
  message.length: !r 100
  min.db: !r 0.1
  max.db: !r 2.0
  db.interval: !r 0.1
  dataframe: !r data.frame(db = seq(from=0.01, to=1, length.out = 10),
                           block.ber = seq(from=0.1, to=0.07, length.out = 10),
                           conv.ber = seq(from=0.09, to=0.011, length.out = 10),
                           turbo.ber = seq(from=0.08, to=0.0085, length.out = 10))
header-includes:
- \usepackage{tikz}
- \usepackage{pgfplots}
- \usepackage{mathtools}
- \usetikzlibrary{arrows,decorations.pathmorphing,backgrounds,positioning,fit,petri,calc}
---

## Simulationsdaten

- Nachrichtenlänge: `r params$message.length`
- SNR Minimum: `r params$min.db`
- SNR Maximum: `r params$max.db`
- SNR Intervall: `r params$db.interval`

## Plot

```{r, echo=FALSE}

df <- params$dataframe

# min.ber <- min(df$block.ber, df$conv.ber, df$turbo.ber)
# max.ber <- max(df$block.ber, df$conv.ber, df$turbo.ber)
min.ber <- min(df$conv.ber, df$turbo.ber)
max.ber <- max(df$conv.ber, df$turbo.ber)

ggplot2::ggplot(df,ggplot2::aes(db)) + 
    # ggplot2::geom_line(ggplot2::aes(y = df$block.ber, colour="Blockkodierung")) +
    ggplot2::geom_line(ggplot2::aes(y = df$conv.ber, colour="Faltungskodierung")) +
    ggplot2::geom_line(ggplot2::aes(y = df$turbo.ber, colour="Turbokodierung")) +
    ggplot2::scale_y_log10(limits = c(min.ber / 2, max.ber * 2)) + 
    ggplot2::xlab("Signal Rausch Verhältnis [dB]") + 
    ggplot2::ylab("Bitfehlerrate") +
    ggplot2::theme(legend.title = ggplot2::element_blank(), 
                   legend.text = ggplot2::element_text(size=16),
                   text = ggplot2::element_text(size=16),
                   axis.title.y = ggplot2::element_text(margin = ggplot2::margin(0,20,0,0)),
                   axis.title.x = ggplot2::element_text(margin = ggplot2::margin(20,0,0,0)))
```

## Statistik

Bitefehlerrate:

```{r qplot, echo=FALSE, message=FALSE}
# df.ber <- data.frame(block = df$block.ber, conv = df$conv.ber, turbo = df$turbo.ber)
df.ber <- data.frame(conv = df$conv.ber, turbo = df$turbo.ber)
summary(df.ber)
```
