---
title: "Convolution"
output: 
  beamer_presentation:
    keep_tex: true
author: Martin Nocker
fontsize: 8pt
params:
  conv.encoder: !r list(N=2, M=2, generators=c(7,5), rsc=FALSE, termination=logical(0), next.state=matrix(c(0,0,1,1,2,2,3,3), ncol =2), prev.state=matrix(c(0,2,-1,-1,-1,-1,0,2,1,3,1,3), ncol =3), output=matrix(c(0,3,2,1,3,0,1,2), ncol =2))
  code: !r c(-3.0409153, -1.3420658, -0.2564390,  2.6875566, -0.3180743, 1.1115148, 0.5514726, 0.8717883, -1.1767475, -1.0351160)
  decoded: !r c(1,0,1,0,0)
  trellis: !r matrix(c(0,NA,NA,NA,-2,NA,2,NA,-2,4,-2,0,2,0,6,0,2,8,NA,NA,10,NA,NA,NA), nrow = 4)
  survivor.states: !r matrix(c(0,0,0,0,0,3,0,3,0,2,0,2,1,3,1,3,0,2,0,2,1,3,1,3), nrow = 4)
  soft.flag: !r TRUE
header-includes:
- \usepackage{tikz}
- \usepackage{pgfplots}
- \usepackage{mathtools}
- \usetikzlibrary{arrows,decorations.pathmorphing,backgrounds,positioning,fit,petri,calc}
---

```{r, include=FALSE}
# transforms an integer value n to a at least min.length bit binary vector
binVector <- function(n, min.length) {

  result <- integer()
  i <- 0
  while (n != 0) {
    result <- c(n %% 2, result)
    n = n %/% 2
    i <- i + 1
  }

  zeros <- rep(0, times = min.length)

  result <- c(zeros, result)

  return(tail(result,min.length))
}

# returns an ordering of the state numbers for a nice state diagram
ordering <- function(num.states, next.state) {
  #next.state <- matrix(rep(0:(num.states-1), each = 2), ncol = 2)
  result <- integer(1)

  n <- 0
  for (i in 2:num.states) {
    n0 <- next.state[n+1,1]
    n1 <- next.state[n+1,2]

    if (n0 %in% result) {
      n <- n1
    }
    else if (n1 %in% result) {
      n <- n0
    }
    else {
      n <- if (n0 > n1) n0 else n1
    }

    result <- c(result, n)
  }

  return(result)
}
```

```{r, include=FALSE}
conv.encoder <- params$conv.encoder

M <- conv.encoder$M
N <- conv.encoder$N
output <- conv.encoder$output
next.state <- conv.encoder$next.state
prev.state <- conv.encoder$prev.state

code <- params$code
if (params$soft.flag) {
  code <- round(code, digits = 1)
  code.hard <- ifelse(code >= 0, 0, 1)
  code.hard <- paste0(" hard input: (",paste0(code.hard, collapse=","),")")
} else {
  code <- ifelse(code >= 0, 0, 1)
}

decoded <- params$decoded
trellis <- params$trellis
survivor.states <- params$survivor.states

num.states <- 2^M

if (num.states > 4) {
  factor = 0.75
} else {
  factor = 1.25
}

tikz.trellis <- ""

## TRELLIS DIAGRAM
# trellis nodes
for (t in 1:ncol(trellis)) {
  for (s in 1:num.states) {

    if (is.na(trellis[s,t])) {
      nodetype <- "freestate"
      value <- ""
    }
    else {
      nodetype <- "state"
      value <- trellis[s,t]
    }
    definition <- paste0("\\node[",nodetype,"]")
    nodename <- paste0("(node",s-1,t-1,")")
    coordinate <- paste0("at (",t-1,",",factor*(-s+1),")")
    label <- paste0("{",value,"}")
    single.node <- paste(definition,nodename,coordinate,label,";")

    tikz.trellis <- paste(tikz.trellis, single.node)
  }
}

# decoded message under trellis diagram
for (t in 0:(length(decoded)-1)) {
  max.state <- num.states - 1
  visibility <- paste0("\\visible<",ncol(trellis)+1,">")
  position <- paste0("($(node",max.state,t,")!0.5!(node",max.state,t+1,")+(0,-.5)$)")
  decoded.bit <- paste0(visibility,"{\\node [orange, font=\\small] at",position," {",decoded[t+1],"};}")
  
  tikz.trellis <- paste(tikz.trellis, decoded.bit)
}

# state labels
for (s in 0:(num.states-1)) {
  value <- paste(binVector(s,M),collapse = "")
  label <- paste0("\\node (statelabel",s,") [left of=node",s,"0] {",value,"};")

  tikz.trellis <- paste(tikz.trellis, label)
}

# time labels
for (t in 0:(ncol(trellis)-1)) {
  label <- paste0("\\node (timelabel",t,") [above of=node0",t,", yshift=-4mm] {",t,"};")

  tikz.trellis <- paste(tikz.trellis, label)
}

# tikz.trellis
x <- 0
for (t in 1:(ncol(trellis)-1)) {
  x.next <- next.state[x+1,decoded[t]+1]
  for (s in 0:(num.states-1)) {

    if (!is.na(trellis[s+1,t])) {
      this.node <- paste0("(node",s,t-1,")")

      if (!is.na(trellis[next.state[s+1,1]+1,t+1])) {
        next.node.0 <- paste0("(node",next.state[s+1,1],t,")")
        label.value.0 <- paste(binVector(output[s+1,1],N),collapse = "")
        label.0 <- paste0("node [sloped, above, very near start] {",label.value.0,"}")
        edge.0 <- paste("\\draw[->]",this.node,"--",next.node.0,label.0,";")
        
        if (s == x && x.next == next.state[s+1,1]) {
          # path of the decoded message will be colored
          color.edge <- paste("\\draw[->, orange]",this.node,"--",next.node.0,label.0,";")
          edge.0 <- paste0("\\alt<",ncol(trellis)+1-t,"-> {",color.edge,"}{",edge.0,"};")
        }
        else if (survivor.states[next.state[s+1,1]+1,t+1] != s) {
          # remove non-survivor paths at the end
          edge.0 <- paste("\\alt<-",ncol(trellis),"> {",edge.0,"}{};")
        }

        tikz.trellis <- paste(tikz.trellis, edge.0)
      }

      if (!is.na(trellis[next.state[s+1,2]+1,t+1])) {
        next.node.1 <- paste0("(node",next.state[s+1,2],t,")")
        label.value.1 <- paste(binVector(output[s+1,2],N),collapse = "")
        label.1 <- paste0("node [sloped, above, very near start] {",label.value.1,"}")
        edge.1 <- paste("\\draw[->, dashed]",this.node,"--",next.node.1,label.1,";")
        
        if (s == x && x.next == next.state[s+1,2]) {
          # path of the decoded message will be colored
          color.edge <- paste("\\draw[->, dashed, orange]",this.node,"--",next.node.1,label.1,";")
          edge.1 <- paste0("\\alt<",ncol(trellis)+1-t,"-> {",color.edge,"}{",edge.1,"};")
        }
        else if (survivor.states[next.state[s+1,2]+1,t+1] != s) {
          # remove non-survivor paths at the end
          edge.1 <- paste("\\alt<-",ncol(trellis),"> {",edge.1,"}{};")
        }

        tikz.trellis <- paste(tikz.trellis, edge.1)
      }
    }
  }
  x <- x.next
}

# add an "no action" overlay to display the disappearing of the non-survivor paths
# additional.slide <- paste0("\\visible<",ncol(trellis)+1,">{};")
# tikz.trellis <- paste(tikz.trellis, additional.slide)

str.decoded <- paste0(decoded, collapse = "")
trellis.decoded <- paste0("\\visible<",ncol(trellis)+1,">{output: (",str.decoded,")};")

# t-axis
# taxis <- paste0("\\draw[->,thick] ($(timelabel0.north)+(0,.5)$) -- ($(timelabel",(ncol(trellis)-1),".north)+(0,.5)$) node [below right] {$t$};")
# tikz.trellis <- paste(tikz.trellis, taxis)
```

## Trellis Diagram

input: (`r code`)

`r if (params$soft.flag) { code.hard }`

\begin{center}
\begin{tikzpicture}[>=stealth, font=\tiny]
\tikzstyle{state} = [draw, circle, teal, thick, text=black, minimum size=3.5mm, inner sep=0mm]
\tikzstyle{freestate} = [circle, teal, fill=teal, minimum size=1mm, inner sep=0mm]

`r tikz.trellis`

\end{tikzpicture}
\end{center}
