---
title: "Turbo Kodierer mit Punktierung"
author: "Witsch Daniel"
date: "18 April 2016"
output: 
  beamer_presentation:
    keep_tex: true
params:
  orig: !r c(1,1,1,0,0,0)
  interl: !r c(1,1,0,0,0)
  parity1: !r c(1,1,1,1,1)
  parity2: !r c(1,1,1,1,1)
  multipl: !r c(1,1,1,1,1)
  result: !r c(1,1,1,1,1,1,0,0,0,0,0,0,0,1,1)
header-includes:
- \usepackage{tikz}
- \usepackage{pgfplots}
- \usetikzlibrary{arrows,decorations.pathmorphing,backgrounds,positioning,fit,petri,calc}

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Turbo-Kodierer mit Punktierung

- Input : `r params$orig`

\begin{center}
\begin{tikzpicture}[node distance=8mm, inner sep=2mm, >=stealth, font=\tiny]

\tikzstyle{decoderStyle} = [rectangle, draw, align=center]
\tikzstyle{deinterleaverStyle} = [rectangle, draw, node distance=4mm]
\tikzstyle{startEndStyle} = [rectangle, draw]
\tikzstyle{depunctureStyle} = [rectangle, draw, node distance=4mm]
\tikzstyle{demultiplexerStyle} = [depunctureStyle]
\tikzstyle{showStyle} = [decoderStyle, thick, draw=red, text=red, inner sep=1mm]
\tikzstyle{showDrawStyle} = [->, red, thick]

\node [node distance=4mm] (demultiplexerTemp) {};
\node [demultiplexerStyle, rotate=90] (demultiplexer) at (demultiplexerTemp.west) {Demultiplexer};
\node [node distance=4mm] (depunctureTemp)[left=of demultiplexerTemp] {};
\node [depunctureStyle, rotate=90] (depuncture) at (depunctureTemp.west) {Depunktierung};
\node [decoderStyle] (decoder1) [above right=of demultiplexerTemp] {Soft-In/Soft-Out\\ Dekodierer 1};
\node [deinterleaverStyle] (interleaver1) [right=of decoder1] {$I$};
\node [deinterleaverStyle] (interleaver2) [above=of interleaver1] {$I^{-1}$};
\node [deinterleaverStyle] (interleaver3) [below=of interleaver1] {$I$};
\node [decoderStyle, node distance=4mm] (decoder2) [right=of interleaver3] {Soft-In/Soft-Out\\ Dekodierer 2};
\node [deinterleaverStyle] (interleaver4) [right=of decoder2] {$I^{-1}$};
\node [startEndStyle] (start) [left=of depunctureTemp] {Input};
\node [startEndStyle, node distance=5mm] (end) [right=of interleaver4] {Output};

\draw [->] (start.east) -- (depuncture.north);
\draw [->] (depuncture.south) -- (demultiplexer.north);
\draw [->] (decoder1.east) -- (interleaver1.west);
\draw [->] (interleaver3.east) -- (decoder2.west);
\draw [->] (decoder2.east) -- (interleaver4.west);
\draw [->] (interleaver4.east) -- (end.west);

\draw [->] ($(decoder2.east)+(0,+.2)$) -| ++(.2,.7) node (afterDecoder2) {} |- (interleaver2.east);
\draw [<-] ($(decoder1.west)+(0,+.2)$) -| ++(-.2,.7) node (afterInterleaver2) {} |- (interleaver2.west);
\draw [<-] ($(decoder1.west)+(0,+.2)$) -- ++(-1.5,0) node [near end, above=-0.1] {jlka};
\draw [->] (interleaver1.east) -| ++(+.2,-.7) node (afterInterleaver1) {} |- ($(decoder2.west)+(0,+.2)$);
\draw [->] ($(demultiplexer.south)+(0,+.4)$) -| ++(+.15,+.2) node (afterDemOrig) {} |- (decoder1.west);
\draw [->] (demultiplexer.south) -| ++(+.3,+.2) node (afterDemParity1) {} |- ($(decoder1.west)+(0,-.2)$);
\draw [->] (afterDemOrig) |- (interleaver3.west);
\draw [<-] ($(decoder2.west)+(0,-.2)$) -| ++(-.2,-.3) node (afterDemParity2) {} |- ($(demultiplexer.south)+(0,-.4)$);

\begin{scope}[on background layer]
\node [draw, fit=(depuncture) (decoder1) (decoder2) (demultiplexer) (interleaver1) (interleaver2) (interleaver3)
(interleaver4)] (background) {};
\end{scope}

\end{tikzpicture}
\end{center}

- Output : `r params$result`
