// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// helloEcpp
SEXP helloEcpp(SEXP greetingPointer);
RcppExport SEXP channelcoding_helloEcpp(SEXP greetingPointerSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type greetingPointer(greetingPointerSEXP);
    __result = Rcpp::wrap(helloEcpp(greetingPointer));
    return __result;
END_RCPP
}
