# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_generateMatrices_nsc <- function(N, M, generator) {
    .Call('channelcoding_c_generateMatrices_nsc', PACKAGE = 'channelcoding', N, M, generator)
}

c_generateMatrices_rsc <- function(N, M, generator) {
    .Call('channelcoding_c_generateMatrices_rsc', PACKAGE = 'channelcoding', N, M, generator)
}

c_convolutionEncode <- function(input, N, M, nextState, output, nsc, termination, terminate) {
    .Call('channelcoding_c_convolutionEncode', PACKAGE = 'channelcoding', input, N, M, nextState, output, nsc, termination, terminate)
}

c_convolutionDecode <- function(code, N, M, previousState, output) {
    .Call('channelcoding_c_convolutionDecode', PACKAGE = 'channelcoding', code, N, M, previousState, output)
}

c_convolutionDecode_hard <- function(code, N, M, previousState, output) {
    .Call('channelcoding_c_convolutionDecode_hard', PACKAGE = 'channelcoding', code, N, M, previousState, output)
}

