# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_generateMatrices <- function(N, M, generator) {
    .Call('channelcoding_c_generateMatrices', PACKAGE = 'channelcoding', N, M, generator)
}

c_generateMatrices_rsc <- function(N, M, generator) {
    .Call('channelcoding_c_generateMatrices_rsc', PACKAGE = 'channelcoding', N, M, generator)
}

c_convolutionEncode <- function(input, N, M, nextState, output, rsc, termination, terminate) {
    .Call('channelcoding_c_convolutionEncode', PACKAGE = 'channelcoding', input, N, M, nextState, output, rsc, termination, terminate)
}

c_convolutionDecode <- function(code, N, M, previousState, output) {
    .Call('channelcoding_c_convolutionDecode', PACKAGE = 'channelcoding', code, N, M, previousState, output)
}

c_convolutionDecode_hard <- function(code, N, M, previousState, output) {
    .Call('channelcoding_c_convolutionDecode_hard', PACKAGE = 'channelcoding', code, N, M, previousState, output)
}

c_insert_dotted_bits <- function(dotted_message, dotting_vector, rows, cols) {
    .Call('channelcoding_c_insert_dotted_bits', PACKAGE = 'channelcoding', dotted_message, dotting_vector, rows, cols)
}

c_turbo_decode <- function(x_noisy, parity_noisy1, parity_noisy2, permutation, N_ITERATION, N, M, previousState, output, output_index) {
    .Call('channelcoding_c_turbo_decode', PACKAGE = 'channelcoding', x_noisy, parity_noisy1, parity_noisy2, permutation, N_ITERATION, N, M, previousState, output, output_index)
}

